---
title: 'Example implementation of variable selection techniques for zero-inflated predictors'
author: "Mariella Gregorich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2:
    css: "src/css_style.css"
    theme: cosmo
    number_sections: true
    keep_md: no
    fig_caption: true
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: true
      smooth_scroll: true
    highlight: tango
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = F, warning=F, message=F)

pacman::p_load(ggplot2, parallel, future.apply, stringr, kableExtra,
               openxlsx, dplyr, tidyverse,tableone,  concreg,
               glmnet, gglasso, oem, WGCNA)
source(here::here("src","functions.R"))

```


# Mosaique cohort

```{r initialization}
# ----------- Initialization
data_mos <- readRDS(here::here("data", "mosaique", "CRS_Mariella.rds"))
data_peptides <- data_mos[,6:ncol(data_mos)]
colnames(data_peptides) <- paste0("P",1:ncol(data_peptides))
rownames(data_peptides) <- paste0("N",1:nrow(data_peptides))
data_peptides <- apply(as.matrix(data_peptides), 2, as.numeric)
clin.vars <- c("HF", "Age", "Sex", "eGFR")

# -------- Peptide subset selection due to computational feasibility based on max non-zero entries
ind <- which(apply(data_peptides,2,assess_nonzeros))
data_peptides <- as.matrix(data_peptides[,ind])
data_mos <- data.frame(cbind(data_mos[,1:5],data_peptides))
```


```{r}
# --- Data Preparation
data_mos$HF <- to_factor(data_mos$HF)
data_mos$Sex <- as.numeric(data_mos$Sex)
data_mos$Age <- as.numeric(data_mos$Age)
data_mos$eGFR <- as.numeric(data_mos$eGFR)
marker.vars <- colnames(data_mos[,!colnames(data_mos) %in% c("fidAuswertung",clin.vars)])

table_vars <- data.frame(print(CreateTableOne(vars=c("Age","Sex", "eGFR", "HF"), data=data_mos), printToggle=F))

table_vars %>%
  mutate(rnames=rownames(table_vars)) %>%
  relocate(rnames, .before=Overall) %>%
  kbl(caption="Study characteristics of the Mosaique cohort", escape = F, row.names = F) %>%
  kable_classic(full_width = T, html_font = "Calibri")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left",fixed_thead = T)
```


```{r finaldata}
x <- data_peptides
colnames(x) <- paste0("x.", colnames(x))
d <- (data_peptides != 0)*1
colnames(d) <- paste0("d.", colnames(d))
xt <- apply(data_peptides, 2, function(x) log2(ifelse(x==0, mean(x[x>0]), x)))
colnames(xt) <- paste0("x.", colnames(xt))
ximp <- apply(data_peptides, 2, function(x) log2(ifelse(x==0, min(x[x>0]), x)))

list.varsel <- list()
list.varsel$all <- c("age", "sex",colnames(data_peptides))
```



# Methods

## Ridge-Garrote

```{r model}
# Data
dataset <- data.frame(log2eGFR = log2(data_mos$eGFR), age=data_mos$Age, sex=data_mos$Sex, x=xt, d=d)
data.obj<-list(x=xt, d=d, clinical=cbind("age"=dataset$age, "sex"=dataset$sex), y=dataset$log2eGFR)

# Ridge-Garrote
fit.garrote <- perform_garrote(data.obj, family="gaussian", cv=10, R=2, nlambda=c(11,11))

# Selected variables
rgarrote.varsel <- names(fit.garrote$fit$coefficients[fit.garrote$fit$coefficients != 0])[-1]
rgarrote.varsel <- str_remove_all(rgarrote.varsel, "x.|d.")
list.varsel$rgarrote <- rgarrote.varsel
```


```{r, fig.align='center', fig.height=4, fig.width=6, fig.cap="Calibration curve of the observed and the fitted values obtained by and L1-norm"}
library(ggplot2)
ggplot(NULL, aes(fit.garrote$fit$fitted.values, dataset$log2eGFR))+
  geom_point()+
  geom_smooth()+
  geom_abline(intercept=0, slope=1) +
  scale_x_continuous("Fitted values") +
  theme_bw()

ggplot(NULL, aes(fit.garrote$fit$fitted.values.L1norm, dataset$log2eGFR))+
  geom_point()+
  geom_smooth()+
  geom_abline(intercept=0, slope=1) +
  scale_x_continuous("Fitted values (L1-Norm)") +
  theme_bw()
```

<br>

```{r, fig.align='center', fig.height=4, fig.width=6, fig.cap="Cross-validated prediction error in which each line corresponds to a sequence of lambda1 values, and the different lambda2 values are the 'inner' loop. The vertical bars refer to standard errors of the prediction errors. The optimal combination of lambda1 and lambda2 is highlighted in black."}

plot.protogarrote(fit.garrote)
```
<br>

```{r, fig.align='center', fig.height=4, fig.width=6, fig.cap="Model coefficients for the continuous and the binary component."}
par(mfrow=c(1,2)) 
p1 <- plot.coefficients.protogarrote(fit.garrote, order="d")
p2 <- plot.coefficients.protogarrote(fit.garrote, order="d", lambda="L1norm")
```

<br>

Performance measures
```{r}
pred <- fit.garrote$fit$fitted.values
obs <- dataset$log2eGFR
tbl_garrote <- eval_performance(pred, obs)

tbl_garrote %>%
  kbl(caption="Performance measures of the Ridge-Garrote model", escape = F, row.names = F, digits = 2) %>%
  kable_classic(full_width = T, html_font = "Calibri")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left",fixed_thead = T)
```


## Ridge-Lasso (adaptive lasso)

```{r}
# Data
dataset <- data.frame(log2eGFR = log2(data_mos$eGFR), xt, d, age=data_mos$Age, sex=data_mos$Sex)
data.obj<-list(x=xt, d=d, clinical=cbind("age"=dataset$age, "sex"=dataset$sex), y=dataset$log2eGFR)

# Adaptive lasso
fit.alasso <- perform_alasso(data.obj=data.obj, family = "gaussian", nlambda = c(11,11), 
                             cv=10, R=1, alpha1 = 0, alpha2 = 1)
pred.lasso <- fit.alasso$fit$fitted.values
#pred.lasso <- predict_garrote(fit.alasso$glmnet.fit.alasso, s=fit.alasso$fit$lambda.min["alasso"], newx=dataset))
```

```{r}
# Selected variables
rlasso.varsel <- names(fit.alasso$fit$coefficients)[which(fit.alasso$fit$coefficients != 0)][-1]
rlasso.varsel <- str_remove_all(rlasso.varsel, "x.|d.")
list.varsel$rlasso <- rlasso.varsel
```

```{r, fig.align='center', fig.height=4, fig.width=6, fig.cap="Calibration curve of the observed and the fitted values obtained by Ridge-Lasso"}
ggplot(NULL, aes(pred.lasso, dataset$log2eGFR))+
  geom_point()+
  geom_smooth()+
  geom_abline(intercept=0, slope=1) +
  scale_x_continuous("Fitted values") +
  theme_bw()
```

<br>

Performance measures
```{r}
pred <- pred.lasso
obs <- dataset$log2eGFR
tbl_rlasso <- eval_performance(pred, obs)

tbl_rlasso %>%
  kbl(caption="Performance measures of the Ridge-Lasso model", escape = F, row.names = F, digits = 2) %>%
  kable_classic(full_width = T, html_font = "Calibri")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left",fixed_thead = T)
```

## Lasso-Ridge

```{r}
# Data for Lasso
dataset <- data.frame(log2eGFR = log2(data_mos$eGFR), age=data_mos$Age, sex=data_mos$Sex, x=ximp)
data.obj<-list(x=ximp, d=d, clinical=cbind("age"=dataset$age, "sex"=dataset$sex), y=dataset$log2eGFR)

# Lasso for selection
# Adaptive lasso
fit.lridge <- perform_lridge(data.obj = data.obj, family = "gaussian", nlambda = c(11,11), cv=10, R=2, alpha1 = 1, alpha2 = 0)
pred.lridge <- fit.lridge$fit$fitted.values
```

```{r}
# Selected variables
lridge.varsel <- names(fit.lridge$fit$coefficients)[which(fit.lridge$fit$coefficients != 0)][-1]
lridge.varsel <- str_remove_all(lridge.varsel, "x.|d.")
list.varsel$lridge <- lridge.varsel
```

```{r, fig.align='center', fig.height=4, fig.width=6, fig.cap="Calibration curve of the observed and the fitted values obtained by Lasso-Ridge"}
ggplot(NULL, aes(pred.lridge, dataset$log2eGFR))+
  geom_point()+
  geom_smooth()+
  geom_abline(intercept=0, slope=1) +
  scale_x_continuous("Fitted values") +
  theme_bw()
```

<br>

Performance measures
```{r}
pred <- pred.lridge
obs <- dataset$log2eGFR
tbl_lridge <- eval_performance(pred, obs)

tbl_lridge %>%
  kbl(caption="Performance measures of the Lasso-Ridge model", escape = F, row.names = F, digits = 2) %>%
  kable_classic(full_width = T, html_font = "Calibri")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left",fixed_thead = T)
```


## Ridge

```{r}
# Data
dataset <- data.frame(log2eGFR = log2(data_mos$eGFR), age=data_mos$Age, sex=data_mos$Sex, xt, d)

# Ridge
cv_ridge <- cv.glmnet(as.matrix(dataset[,-1]), dataset$log2eGFR, alpha = 0)
fit.ridge <- glmnet(as.matrix(dataset[,-1]), dataset$log2eGFR, alpha = 0, lambda = cv_ridge$lambda.min)
pred.ridge <- c(predict.glmnet(fit.ridge, s=cv_ridge$lambda.min, type = "response", newx=as.matrix(dataset[,-1])))

```


```{r}
# Selected variables
ridge.varsel <- names(coef(fit.ridge)[which(coef(fit.ridge) != 0),])[-1]
ridge.varsel <- str_remove_all(ridge.varsel, "x.|d.")
list.varsel$ridge <- ridge.varsel
```

```{r, fig.align='center', fig.height=4, fig.width=6, fig.cap="Calibration curve of the observed and the fitted values obtained by Lasso-Ridge"}
ggplot(NULL, aes(pred.ridge, dataset$log2eGFR))+
  geom_point()+
  geom_smooth()+
  geom_abline(intercept=0, slope=1) +
  scale_x_continuous("Fitted values") +
  theme_bw()
```

<br>

Performance measures
```{r}
pred <- pred.ridge
obs <- dataset$log2eGFR
tbl_ridge <- eval_performance(pred, obs)

tbl_ridge %>%
  kbl(caption="Performance measures of the Ridge model", escape = F, row.names = F, digits = 2) %>%
  kable_classic(full_width = T, html_font = "Calibri")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left",fixed_thead = T)
```


## Lasso

```{r}
# Data for Lasso
dataset <- data.frame(log2eGFR = log2(data_mos$eGFR), age=data_mos$Age, sex=data_mos$Sex, x=ximp)

# Lasso for selection
cv_lasso <- cv.glmnet(as.matrix(dataset[,-1]), dataset$log2eGFR, alpha = 1)
fit.lasso <- glmnet(as.matrix(dataset[,-1]), dataset$log2eGFR, alpha = 1, lambda = cv_lasso$lambda.min)
pred.lasso <- c(predict.glmnet(fit.lasso, s=cv_lasso$lambda.min, newx=as.matrix(dataset[,-1])))

```

```{r}
# Selected variables
lasso.varsel <- names(coef(fit.lasso)[which(coef(fit.lasso) != 0),])[-1]
lasso.varsel <- str_remove_all(lasso.varsel, "x.|d.")
list.varsel$lasso <- lasso.varsel
```

```{r, fig.align='center', fig.height=4, fig.width=6, fig.cap="Calibration curve of the observed and the fitted values obtained by Ridge-Lasso"}
ggplot(NULL, aes(pred.lasso, dataset$log2eGFR))+
  geom_point()+
  geom_smooth()+
  geom_abline(intercept=0, slope=1) +
  scale_x_continuous("Fitted values") +
  theme_bw()
```

<br>

Performance measures
```{r}
pred <- pred.lasso
obs <- dataset$log2eGFR
tbl_lasso <- eval_performance(pred, obs)

tbl_lasso %>%
  kbl(caption="Performance measures of the Lasso model", escape = F, row.names = F, digits = 2) %>%
  kable_classic(full_width = T, html_font = "Calibri")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left",fixed_thead = T)
```


# Results

```{r}
tbl_res <- data.frame(rbind(tbl_garrote, tbl_rlasso, tbl_lridge, 
                            tbl_oem, tbl_multi,
                            tbl_lasso, tbl_ridge)) 

tbl_res %>%
  mutate("method"=c("ridge-garrote", "ridge-lasso", "lasso-ridge", 
                    "network-based penalization", "multiple univariable models", 
                    "lasso", "ridge")) %>%
  relocate(method, .before = 1) %>%
  kbl(caption="Performance measures of the network-based froup penalization model", escape = F, row.names = F, digits = 3) %>%
  kable_classic(full_width = T, html_font = "Calibri")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left",fixed_thead = T)
```

<br>

```{r, fig.align='center', fig.width=6, fig.height=6, fig.caption="Venn diagramm of selected predictors by the dfferent methods"}
library(ggvenn)
library(RColorBrewer)

# Prepare a palette of 3 colors with R colorbrewer:
myCol <- brewer.pal(5, "Pastel2")

# Chart
ggvenn(
  list.varsel,
  fill_color = myCol,
  stroke_size = 0.5, set_name_size = 4
)
```

