---
title: "Simulation study - Variable selection for 'too' many zero-inflated predictors (ZIPSel)"
author:
  - name: "Mariella Gregorich"
    affiliation: "Medical University of Vienna, Center for Medical Data Science"
date: last-modified
categories: [2023, simulation study, ZIPSel, R]
description: "Classification: confidential"
editor: visual
theme: cosmo
toc: true  
number-sections: true
colorlinks: true
highlight-style: pygments
format:
  html: 
    code-fold: true
    code-tools: true
    html-math-method: katex
    self-contained: true
---

# Preliminaries

```{r }
rm(list=ls())

source(here::here("src","functions_sim.R"))
source(here::here("src","functions_aux.R"))
#source(here::here("src","setup.R"))

pacman::p_load(ggplot2, parallel, future.apply, stringr, kableExtra,
               openxlsx, dplyr, tidyverse, simdata, looplot, gt)

# Paths
out.path <- "output"
sim.date <- "2023-11-08"
sim.file <- paste0("sim_", sim.date,"/")
sim.path <- here::here(out.path, sim.file)
ggcols <- c("black", "grey20","grey45","goldenrod3", "deepskyblue3",
            "royalblue3", "darkred")
methnames <- c("oracle", "ridge-oracle","lasso", "ridge", "ridge-lasso",
               "lasso-ridge", "ridge-garrote")
# Read in results
tbl_res <- readRDS(here::here(sim.path, "tbl_results_perf.rds"))

tbl_perf <- tbl_res$tbl_perf  %>% 
  mutate(model = fct_relevel(model, methnames))
tbl_varsel <- tbl_res$tbl_varsel %>% 
  mutate(model = fct_relevel(model, methnames))
tbl_allsel <- tbl_res$tbl_allsel %>% 
  mutate(model = fct_relevel(model, methnames))
tbl_groupsel <- tbl_res$tbl_groupsel%>% 
  mutate(model = fct_relevel(model, methnames))
```

# Scenario A

## RMSPE

```{r}
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, 
                revzi, model, penalty, RMSPE.est, RMSPE.lo, RMSPE.up) %>%
  filter(population %in% "A" & epslvl == "none" & revzi == TRUE & struczero == 0.33 & UDdepen == "U" &
           model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  ggplot(aes(x=n, y=RMSPE.est, colour = model, group = model, ymin = RMSPE.lo, ymax=  RMSPE.up)) + 
      geom_point() + 
      geom_line() +
      geom_errorbar(width=0.25) +
      scale_y_continuous(name="RMSPE") +
      scale_color_manual(values = ggcols[-1]) +
      facet_grid(UDdepen ~ propzi) +
      theme_bw()  +
      theme(text = element_text(size=16), strip.text = element_text(size=18))
```

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, 
                revzi, model, penalty, RMSPE.est) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == TRUE & 
           model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  mutate(RMSPE.est = ifelse(UDdepen == "U", RMSPE.est/10, RMSPE.est)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), 
              values_from = RMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" ,
                   grid_rows = "struczero",
                   steps_y_base = -0.5, steps_y_height = 0.1, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged RMSPE",
                   spu_x_shift = 1.5,
                   grid_scales="free_y",
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, 
                   steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(1, 0.5),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi,
                model, penalty, RMSPE.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == TRUE & 
           model != "oracle" ) %>%
  mutate(n = to_factor(n),
         RMSPE.est = ifelse(UDdepen == "U", RMSPE.est/10, RMSPE.est)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), 
              values_from = RMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , 
                   grid_rows = "struczero",
                   steps_y_base = -1, steps_y_height = 0.15, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged RMSPE",
                   spu_x_shift = 1.5,
                   grid_scales="free_y",
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(1, 0.5),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly decreasing proportion of zero-inflation of starting from 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, 
                revzi, model, penalty, RMSPE.est) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == FALSE & 
           model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  mutate(RMSPE.est = ifelse(UDdepen == "U", RMSPE.est/10, RMSPE.est)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), 
              values_from = RMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" ,
                   grid_rows = "struczero",
                   steps_y_base = -0.5, steps_y_height = 0.1, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged RMSPE",
                   spu_x_shift = 1.5,
                   grid_scales="free_y",
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, 
                   steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(1, 0.5),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly decreasing proportion of zero-inflation of starting from 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi,
                model, penalty, RMSPE.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == FALSE & 
           model != "oracle" ) %>%
  mutate(n = to_factor(n),
         RMSPE.est = ifelse(UDdepen == "U", RMSPE.est/10, RMSPE.est)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), 
              values_from = RMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , 
                   grid_rows = "struczero",
                   steps_y_base = -1, steps_y_height = 0.15, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged RMSPE",
                   spu_x_shift = 1.5,
                   grid_scales="free_y",
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(1, 0.5),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

## Relative RMSPE

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, relRMSPE.est) %>%
  filter(population %in% "A"  & propzi == 0.75 & revzi == TRUE & model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = relRMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , 
                   grid_rows = "struczero",
                   steps_y_base = 0.5, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged relative RMSPE",
                   spu_x_shift = 1.5,
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.5, 0.25),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up tp 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model,
                penalty, relRMSPE.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == TRUE & model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = relRMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , 
                   grid_rows = "struczero",
                   steps_y_base = 0.75, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged relative RMSPE",
                   spu_x_shift = 1.5,
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.5, 0.25),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly decreasing proportion of zero-inflation of starting from 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, relRMSPE.est) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == FALSE & model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = relRMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = 0.5, steps_y_height = 0.1, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged relative RMSPE",
                   spu_x_shift = 1.5,
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.5, 0.25),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly decreasing proportion of zero-inflation of starting from 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model,
                penalty, relRMSPE.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == FALSE & model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = relRMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = 0.5, steps_y_height = 0.1, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged relative RMSPE",
                   spu_x_shift = 1.5,
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(1, 0.5),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

## Calibration

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, CS.est) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == TRUE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = CS.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged CS",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.5, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 25%"
tbl_perf %>%
  dplyr::select(population,  UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, CS.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == TRUE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = CS.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = 0.25, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged CS",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.25, 0.25),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly decreasing proportion of zero-inflation of starting from 75%"
tbl_perf %>%
  dplyr::select(population,  UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, CS.est) %>%
  filter(population %in% "A"  & propzi == 0.75 & revzi == FALSE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = CS.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = 0.0, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged CS",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(1, 0.25),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly decreasing proportion of zero-inflation of starting from 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, CS.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == FALSE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = CS.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = 0.25, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged CS",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.5, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

## R2

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, R2.est) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == TRUE ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = R2.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.15, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged R2",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, R2.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == TRUE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = R2.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.15, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged R2",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly decreasing proportion of zero-inflation of starting from 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, R2.est) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == FALSE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = R2.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.15, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged R2",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly decreasing proportion of zero-inflation of starting from 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, R2.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == FALSE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = R2.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.15, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged R2",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

## Variable selection

### Variable inclusion

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, npeps.est) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == TRUE ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = npeps.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -25, steps_y_height = 5, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged number of incuded peptides",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(50, 15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a linearly increasing proportion of zero-inflation of up to 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, npeps.est) %>%
  filter(population %in% "A"  & propzi == 0.25 & revzi == TRUE ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = npeps.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -25, steps_y_height = 5, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged number of incuded peptides",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(50, 15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, npeps.est) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == FALSE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = npeps.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -25, steps_y_height = 5, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged number of incuded peptides",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(50, 15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population A with a denearly increasing proportion of zero-inflation starting with 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, npeps.est) %>%
  filter(population %in% "A" & propzi == 0.25 & revzi == FALSE ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = npeps.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -25, steps_y_height = 5, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged number of incuded peptides",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(50, 15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

### Discovery rates

::: panel-tabset
#### TPDR

```{r}
#| fig-cap: "population A with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_allsel %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, TPDR) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == TRUE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = TPDR, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.025, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "True-postive discovery rate",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.1),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

#### TNDR

```{r}
#| fig-cap: "population A with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_allsel %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, TNDR) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == TRUE ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = TNDR, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.025, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "True-postive discovery rate",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.1),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

#### FPDR

```{r}
#| fig-cap: "population A with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_allsel %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, FPDR) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == TRUE ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = FPDR, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.025, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "True-postive discovery rate",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.1, 0.1),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

#### FNDR

```{r}
#| fig-cap: "population A with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_allsel %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, revzi, model, penalty, FNDR) %>%
  filter(population %in% "A" & propzi == 0.75 & revzi == TRUE) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = FNDR, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.025, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "False-negative discovery rate",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.1),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```
:::

# Scenario B

## RMSPE

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, model, penalty, RMSPE.est) %>%
  filter(population %in% "B" & propzi == 0.75 & model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  mutate(RMSPE.est = ifelse(UDdepen == "U", RMSPE.est/10, RMSPE.est)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), 
              values_from = RMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" ,
                   grid_rows = "struczero",
                   steps_y_base = -0.5, steps_y_height = 0.1, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged RMSPE",
                   spu_x_shift = 1.5,
                   grid_scales="free_y",
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, 
                   steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(1, 0.5),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, model, penalty, RMSPE.est) %>%
  filter(population %in% "B" & propzi == 0.25 & model != "oracle" ) %>%
  mutate(n = to_factor(n),
         RMSPE.est = ifelse(UDdepen == "U", RMSPE.est/10, RMSPE.est)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), 
              values_from = RMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , 
                   grid_rows = "struczero",
                   steps_y_base = -1, steps_y_height = 0.15, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged RMSPE",
                   spu_x_shift = 1.5,
                   grid_scales="free_y",
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(1, 0.5),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```



## Relative RMSPE

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, model, penalty, relRMSPE.est) %>%
  filter(population %in% "B"  & propzi == 0.75 & model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = relRMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , 
                   grid_rows = "struczero",
                   steps_y_base = 0.5, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged relative RMSPE",
                   spu_x_shift = 1.5,
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.5, 0.25),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up tp 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, model, penalty, relRMSPE.est) %>%
  filter(population %in% "B" & propzi == 0.25 &  model != "oracle") %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = relRMSPE.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , 
                   grid_rows = "struczero",
                   steps_y_base = 0.75, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged relative RMSPE",
                   spu_x_shift = 1.5,
                   colors = ggcols[-1],
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.5, 0.25),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

## Calibration

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, model, penalty, CS.est) %>%
  filter(population %in% "B" & propzi == 0.75 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = CS.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged CS",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.5, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 25%"
tbl_perf %>%
  dplyr::select(population,  UDdepen, n, epslvl, propzi, struczero, model, penalty, CS.est) %>%
  filter(population %in% "B" & propzi == 0.25 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = CS.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = 0.25, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged CS",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 1,
                   y_expand_add = c(0.25, 0.25),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```


## R2

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero,  model, penalty, R2.est) %>%
  filter(population %in% "B" & propzi == 0.75 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = R2.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.15, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged R2",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, model, penalty, R2.est) %>%
  filter(population %in% "B" & propzi == 0.25 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = R2.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.15, steps_y_height = 0.05, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged R2",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```



## Variable selection

### Variable inclusion

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 75%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero,  model, penalty, npeps.est) %>%
  filter(population %in% "B" & propzi == 0.75 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = npeps.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -25, steps_y_height = 5, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged number of incuded peptides",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(50, 15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

```{r}
#| fig-cap: "population B with a linearly increasing proportion of zero-inflation of up to 25%"
tbl_perf %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero,  model, penalty, npeps.est) %>%
  filter(population %in% "B"  & propzi == 0.25  ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = npeps.est, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -25, steps_y_height = 5, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "Averaged number of incuded peptides",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(50, 15),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```


### Discovery rates

::: panel-tabset
#### TPDR

```{r}
#| fig-cap: "population B with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_allsel %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero, model, penalty, TPDR) %>%
  filter(population %in% "B" & propzi == 0.75 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = TPDR, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.025, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "True-postive discovery rate",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.1),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

#### TNDR

```{r}
#| fig-cap: "population B with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_allsel %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero,  model, penalty, TNDR) %>%
  filter(population %in% "B" & propzi == 0.75 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = TNDR, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.025, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "True-postive discovery rate",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.1),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

#### FPDR

```{r}
#| fig-cap: "population B with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_allsel %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero,  model, penalty, FPDR) %>%
  filter(population %in% "B" & propzi == 0.75 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = FPDR, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.025, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "True-postive discovery rate",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.1, 0.1),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```

#### FNDR

```{r}
#| fig-cap: "population B with a denearly increasing proportion of zero-inflation starting with 75%"
tbl_allsel %>%
  dplyr::select(population, UDdepen, n, epslvl, propzi, struczero,  model, penalty, FNDR) %>%
  filter(population %in% "B" & propzi == 0.75 ) %>%
  mutate(n = to_factor(n)) %>%
  arrange(model, penalty) %>%
  pivot_wider(id_cols = c(UDdepen, n, epslvl, struczero), values_from = FNDR, names_from = model) %>%
  nested_loop_plot(x = "n", steps = "epslvl", grid_cols ="UDdepen" , grid_rows = "struczero",
                   steps_y_base = -0.1, steps_y_height = 0.025, 
                   steps_names = "Residual variance",
                   x_name = "Sample size", y_name = "False-negative discovery rate",
                   spu_x_shift = 1.5,
                   colors = ggcols,
                   steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                   hline_intercept = 0,
                   y_expand_add = c(0.15, 0.1),
                   post_processing = list(
                       add_custom_theme = list(
                         text=element_text(size = 14),
                           axis.text.x = element_text(size = 14,
                                                      angle = -90,
                                                      vjust = 0.5),
                         legend.position="top")
                   )) 
```
:::
